up:
	goose postgres "host=localhost port=5432 user=root password=123456 dbname=lenslocked sslmode=disable" up
down:
	goose postgres "host=localhost port=5432 user=root password=123456 dbname=lenslocked sslmode=disable" down
status:
	goose postgres "host=localhost port=5432 user=root password=123456 dbname=lenslocked sslmode=disable" status